
version: '3'

services:
  it-tools:
    image: corentinth/it-tools 
    container_name: it-tools
    restart: always
    ports:
      - "8080:8080"

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database 

  cloudbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    ports:
      - "8081:8080"
    networks:
      - postgres

  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    ports:
      - "8082:3001"

networks:
  postgres:
    driver: bridge

volumes:
  data:
